### ISSUE TITLE
Ошибка копирования по ссылке

### ISSUE THREAD

**Issue by Karnah** [Chloy/University#1]
Добрый день.
Нашёл Вашу проблему. Дело в том, что массивы - ссылочные типы, поэтому если присвоить значение в новую переменную, а потом отредактировать её, то также будет изменён исходный массив. То есть всё дело вот в этих строках:
https://github.com/Chloy/University/blob/dba919b56dd62d755b52c538ad5e7f27fb61a2e4/C%23/CourseWork/Encoder/Encrypter/MyBlowfish.cs#L197-L198
https://github.com/Chloy/University/blob/dba919b56dd62d755b52c538ad5e7f27fb61a2e4/C%23/CourseWork/Encoder/MyBlowfish/MyBlowfish.cs#L197-L198

При инициализации класса, он меняет данные в своём поле, но также меняются данные и в статическом поле. Поэтому второй созданный класс уже работает с "грязными" данными. Исправить эту проблему очень просто, достаточно создавать копию массива при инициализации:
``` C#
uint[] PKeys = (uint[])_PKeys.Clone();
uint[,] SKeys = (uint[,])_SBlocks.Clone();
```
Таким образом, исходный массив не будет изменяться.

**Comment by Chloy** [comment]
> 
> 
> Добрый день.
> Нашёл Вашу проблему. Дело в том, что массивы - ссылочные типы, поэтому если присвоить значение в новую переменную, а потом отредактировать её, то также будет изменён исходный массив. То есть всё дело вот в этих строках:
> 
> https://github.com/Chloy/University/blob/dba919b56dd62d755b52c538ad5e7f27fb61a2e4/C%23/CourseWork/Encoder/Encrypter/MyBlowfish.cs#L197-L198
> 
> https://github.com/Chloy/University/blob/dba919b56dd62d755b52c538ad5e7f27fb61a2e4/C%23/CourseWork/Encoder/MyBlowfish/MyBlowfish.cs#L197-L198
> 
> При инициализации класса, он меняет данные в своём поле, но также меняются данные и в статическом поле. Поэтому второй созданный класс уже работает с "грязными" данными. Исправить эту проблему очень просто, достаточно создавать копию массива при инициализации:
> 
> ```cs
> uint[] PKeys = (uint[])_PKeys.Clone();
> uint[,] SKeys = (uint[,])_SBlocks.Clone();
> ```
> 
> Таким образом, исходный массив не будет изменяться.

**Comment by Chloy** [comment]
Большое спасибо.
